import { ethers } from 'ethers';
import { env } from './env';

// ============================================================
// Singleton provider/wallet/contract setup
// ============================================================

let provider: ethers.JsonRpcProvider | null = null;
let wallet: ethers.Wallet | null = null;
let contract: ethers.Contract | null = null;

function getProvider(): ethers.JsonRpcProvider {
  if (!provider) {
    // Upgraded to use Amazon Managed Blockchain (AMB) Access if AMB_ENDPOINT is provided
    const rpcUrl = env.AMB_ENDPOINT || env.POLYGON_RPC_URL;
    provider = new ethers.JsonRpcProvider(rpcUrl);
    console.log(`[blockchain] Connected to network via: ${env.AMB_ENDPOINT ? 'AWS AMB' : 'Public RPC'}`);
  }
  return provider;
}

function getWallet(): ethers.Wallet | null {
  if (!wallet && env.PRIVATE_KEY) {
    wallet = new ethers.Wallet(env.PRIVATE_KEY, getProvider());
  }
  return wallet;
}

async function getContract(): Promise<ethers.Contract | null> {
  if (contract) return contract;

  const contractAddress = env.CONTRACT_ADDRESS;
  if (!contractAddress) {
    console.warn('[blockchain] CONTRACT_ADDRESS not set — blockchain calls will be skipped.');
    return null;
  }

  try {
    // ABI generated by: npx hardhat compile
    // eslint-disable-next-line @typescript-eslint/no-var-requires
    const artifact = require('../../artifacts/contracts/HoneyChain.sol/HoneyChain.json') as {
      abi: ethers.InterfaceAbi;
    };
    const signerOrProvider = getWallet() ?? getProvider();
    contract = new ethers.Contract(contractAddress, artifact.abi, signerOrProvider);
    return contract;
  } catch {
    console.warn("[blockchain] HoneyChain ABI not found. Run 'npx hardhat compile' first.");
    return null;
  }
}

// ============================================================
// Hash Utilities
// ============================================================

/**
 * Compute the keccak256 hash of a batch code string.
 * This is what the smart contract uses as the mapping key.
 */
export function hashBatchCode(batchCode: string): string {
  return ethers.id(batchCode); // ethers.id() = keccak256(utf8 string)
}

/**
 * Convert a hex string hash to bytes32 for Solidity.
 */
export function toBytes32(hexHash: string): string {
  return ethers.zeroPadValue(hexHash, 32);
}

// ============================================================
// Write Functions (require PRIVATE_KEY)
// ============================================================

/**
 * Register a new honey batch on-chain.
 * Called after IPFS upload — both CID and hash are known.
 */
export async function createBatchOnChain(params: {
  batchCode: string;
  harvestTimestamp: number;
  quantityGrams: number;
  metadataCID: string;
  metadataHash: string;
}): Promise<string> {
  const c = await getContract();
  if (!c) throw new Error('[blockchain] Contract not initialized — cannot createBatch');

  const batchIdHash = hashBatchCode(params.batchCode);
  const metadataHashBytes = ethers.getBytes(params.metadataHash);

  const tx = await c.createBatch(
    batchIdHash,
    params.harvestTimestamp,
    params.quantityGrams,
    params.metadataCID,
    metadataHashBytes
  );
  const receipt = await tx.wait();
  if (!receipt) throw new Error('[blockchain] Transaction receipt not received');
  return receipt.hash as string;
}

/**
 * Commit a lab certificate hash on-chain.
 * Called after the lab PDF is uploaded to IPFS.
 */
export async function verifyLabOnChain(params: {
  batchCode: string;
  labReportHash: string;
}): Promise<string> {
  const c = await getContract();
  if (!c) throw new Error('[blockchain] Contract not initialized');

  const batchIdHash = hashBatchCode(params.batchCode);
  const labHashBytes = ethers.getBytes(params.labReportHash);

  const tx = await c.verifyLab(batchIdHash, labHashBytes);
  const receipt = await tx.wait();
  if (!receipt) throw new Error('[blockchain] Transaction receipt not received');
  return receipt.hash as string;
}

/**
 * Transfer custody of a batch to the next supply chain actor.
 */
export async function transferCustodyOnChain(params: {
  batchCode: string;
  toAddress: string;
  newStatus: number; // BatchStatus enum value (0-8)
}): Promise<string> {
  const c = await getContract();
  if (!c) throw new Error('[blockchain] Contract not initialized');

  const batchIdHash = hashBatchCode(params.batchCode);
  const tx = await c.transferCustody(batchIdHash, params.toAddress, params.newStatus);
  const receipt = await tx.wait();
  if (!receipt) throw new Error('[blockchain] Transaction receipt not received');
  return receipt.hash as string;
}

/**
 * Package a batch — records jar count, jar size, and updated IPFS metadata.
 */
export async function packageBatchOnChain(params: {
  batchCode: string;
  jarCount: number;
  jarSizeGrams: number;
  newMetadataCID: string;
  newMetadataHash: string;
}): Promise<string> {
  const c = await getContract();
  if (!c) throw new Error('[blockchain] Contract not initialized');

  const batchIdHash = hashBatchCode(params.batchCode);
  const metadataHashBytes = ethers.getBytes(params.newMetadataHash);

  const tx = await c.packageBatch(
    batchIdHash,
    params.jarCount,
    params.jarSizeGrams,
    params.newMetadataCID,
    metadataHashBytes
  );
  const receipt = await tx.wait();
  if (!receipt) throw new Error('[blockchain] Transaction receipt not received');
  return receipt.hash as string;
}

/**
 * Recall a batch. Admin-only. All subsequent QR scans will show red alert.
 */
export async function recallBatchOnChain(params: {
  batchCode: string;
  reasonCID: string;
}): Promise<string> {
  const c = await getContract();
  if (!c) throw new Error('[blockchain] Contract not initialized');

  const batchIdHash = hashBatchCode(params.batchCode);
  const tx = await c.recallBatch(batchIdHash, params.reasonCID);
  const receipt = await tx.wait();
  if (!receipt) throw new Error('[blockchain] Transaction receipt not received');
  return receipt.hash as string;
}

// ============================================================
// Read Functions (no gas, no PRIVATE_KEY needed)
// ============================================================

export interface ChainBatchRecord {
  batchIdHash: string;
  beekeeper: string;
  currentCustodian: string;
  harvestTimestamp: number;
  createdAt: number;
  quantityGrams: number;
  status: number;
  metadataCID: string;
  metadataHash: string;
  labReportHash: string;
  labVerified: boolean;
  recalled: boolean;
}

/**
 * Read the full batch record from the blockchain.
 * Returns null if the contract is not available or batch doesn't exist.
 */
export async function getBatchFromChain(batchCode: string): Promise<ChainBatchRecord | null> {
  const c = await getContract();
  if (!c) return null;

  try {
    const batchIdHash = hashBatchCode(batchCode);
    const raw = await c.getBatch(batchIdHash);

    // ethers returns struct fields as array indices when ABI is not fully typed
    return {
      batchIdHash:      raw.batchIdHash as string,
      beekeeper:        raw.beekeeper as string,
      currentCustodian: raw.currentCustodian as string,
      harvestTimestamp: Number(raw.harvestTimestamp),
      createdAt:        Number(raw.createdAt),
      quantityGrams:    Number(raw.quantityGrams),
      status:           Number(raw.status),
      metadataCID:      raw.metadataCID as string,
      metadataHash:     raw.metadataHash as string,
      labReportHash:    raw.labReportHash as string,
      labVerified:      raw.labVerified as boolean,
      recalled:         raw.recalled as boolean,
    };
  } catch (err) {
    console.error('[blockchain] getBatch error:', err);
    return null;
  }
}

/**
 * Lightweight status check — avoids fetching the full struct.
 */
export async function getBatchStatusFromChain(
  batchCode: string
): Promise<{ status: number; recalled: boolean; labVerified: boolean } | null> {
  const c = await getContract();
  if (!c) return null;

  try {
    const batchIdHash = hashBatchCode(batchCode);
    const [status, recalled, labVerified] = await c.getBatchStatus(batchIdHash) as [bigint, boolean, boolean];
    return { status: Number(status), recalled, labVerified };
  } catch (err) {
    console.error('[blockchain] getBatchStatus error:', err);
    return null;
  }
}
